# Generated by Django 5.1.6 on 2025-02-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Ölkə',
                'verbose_name_plural': 'Ölkələr',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.country', verbose_name='Ölkə')),
            ],
            options={
                'verbose_name': 'Şəhər',
                'verbose_name_plural': 'Şəhərlər',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=255, verbose_name='Soyad')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Telefon')),
                ('address', models.CharField(max_length=255, verbose_name='Ünvan')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Poçt kodu')),
                ('fin_code', models.CharField(max_length=7, unique=True, verbose_name='Fin kod')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/Y/d/m/')),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city', verbose_name='Şəhər')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.country', verbose_name='Ölkə')),
            ],
            options={
                'verbose_name': 'İstifadəçi',
                'verbose_name_plural': 'İstifadəçilər',
            },
        ),
    ]
