# Generated by Django 5.1.4 on 2025-01-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fin_code',
            field=models.CharField(max_length=7, unique=True, verbose_name='Fin kod'),
        ),
    ]
