# Generated by Django 5.1.6 on 2025-02-11 20:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kupon')),
                ('valid_from', models.DateTimeField(verbose_name='Güvvəyə minir')),
                ('valid_to', models.DateTimeField(verbose_name='Güvvədən düşür')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Güzəşt')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('used_by_fin_codes', models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL, verbose_name='İstifadə edilmiş fin kodlar')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
            },
        ),
    ]
