# Generated by Django 5.1.4 on 2024-12-11 17:35

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiallar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slaq'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slaq'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=20, verbose_name='Artikul'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilib'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[shop.models.validate_discount], verbose_name='Endirim (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveSmallIntegerField(verbose_name='Stokda olan miqdar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='Slaq'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yenilənib'),
        ),
        migrations.CreateModel(
            name='WeightOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Çəki (q)')),
                ('carat', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Karat')),
                ('size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ölçü (mm)')),
                ('price_modifier', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Çəkiyə görə qiymət')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_options', to='shop.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Çəki seçimi',
                'verbose_name_plural': 'Çəki seçimləri',
            },
        ),
    ]
