# Generated by Django 5.1.6 on 2025-02-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('image', models.ImageField(upload_to='slider', verbose_name='Şəkil')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='shop.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayderlər',
                'ordering': ['-created_at'],
            },
        ),
    ]
