# Generated by Django 5.1.4 on 2025-01-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100, verbose_name='Başlıq')),
                ('description', models.TextField(default='Description', verbose_name='Təsvir')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
    ]
