# Generated by Django 5.1.6 on 2025-02-11 20:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('description', tinymce.models.HTMLField(verbose_name='Təsvir')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma tarixi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Çatdırılma məlumatı',
                'verbose_name_plural': '6. Çatdırılma məlumatı',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt')),
            ],
            options={
                'verbose_name': 'E-poçt',
                'verbose_name_plural': '3. E-poçtlar',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('image', models.ImageField(upload_to='feature/', verbose_name='Şəkil')),
                ('description', tinymce.models.HTMLField(verbose_name='Təsvir')),
            ],
            options={
                'verbose_name': 'Xüsusiyyət',
                'verbose_name_plural': '8. Xüsusiyyətlər',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Telefon',
                'verbose_name_plural': '2. Telefonlar',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('description', tinymce.models.HTMLField(verbose_name='Təsvir')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma tarixi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Məxfilik Siyasəti',
                'verbose_name_plural': '5. Məxfilik Siyasəti',
            },
        ),
        migrations.CreateModel(
            name='ReturnsAndRefunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('description', tinymce.models.HTMLField(verbose_name='Təsvir')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma tarixi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Qaytarmalar və Geri Ödənişlər',
                'verbose_name_plural': '7. Geri ödəniş',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('description', tinymce.models.HTMLField(verbose_name='Təsvir')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma tarixi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Qaydalar və Şərtlər',
                'verbose_name_plural': '4. Qaydalar və Şərtlər',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='')),
                ('email', models.ManyToManyField(to='parameters.email', verbose_name='E-poçt')),
                ('phone', models.ManyToManyField(to='parameters.phone', verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Əlaqə mməluamtı',
                'verbose_name_plural': '1. Əlaqə məluamtları',
            },
        ),
    ]
