# Generated by Django 5.1.4 on 2025-01-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_email_phone_alter_feature_options_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma tarixi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'Məxfilik Siyasəti',
                'verbose_name_plural': 'Məxfilik Siyasəti',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Əlaqə mməluamtı', 'verbose_name_plural': 'Əlaqə mməluamtları'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-id'], 'verbose_name': 'Xüsusiyyət', 'verbose_name_plural': '1. Xüsusiyyətlər'},
        ),
    ]
