# Generated by Django 5.1.4 on 2025-01-11 20:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_privacypolicy_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Təsvir'),
        ),
    ]
