# Generated by Django 5.1.4 on 2025-01-03 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=60, verbose_name='Soyad')),
                ('fin_code', models.CharField(max_length=7, verbose_name='Fin kod')),
                ('email', models.EmailField(max_length=254, verbose_name='E=poçt')),
                ('country', models.CharField(max_length=50, verbose_name='Ölkə')),
                ('city', models.CharField(max_length=50, verbose_name='Bölgə')),
                ('address', models.CharField(max_length=100, verbose_name='Ünvan')),
                ('postal_code', models.CharField(max_length=50, verbose_name='Poçt kodu')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefon')),
                ('status', models.CharField(choices=[('PENDING', 'Emal gözlənilir'), ('PROCESSING', 'Emal edilir'), ('SHIPPED', 'Göndərilib'), ('IN_TRANSIT', 'Yoldadır'), ('DELIVERED', 'Çatdırıldı'), ('CANCELLED', 'Ləğv edildi'), ('RETURNED', 'Qaytarıldı'), ('FAILED', 'Çatdırılma uğursuz oldu')], default='PENDING', max_length=23, verbose_name='Çatdırılma statusu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sifariş tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('paid', models.BooleanField(default=False, verbose_name='Ödənilib')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alınan qiymət')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product', verbose_name='Məhsul')),
                ('weight_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.weightoption', verbose_name='Выбранный вес')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
    ]
